### ISSUE TITLE
Database errors when viewing clients/contracts

### ISSUE THREAD

**Issue by lpetersctc** [PavelBastov/opencbs#831]
When trying to view existing clients or contracts, it seems that as soon as a contract is created against a client, I can no longer access the relevant client or their contract.

It throws an exception of "Invalid object name 'dbo.InterestWriteOffEvents'." although there have been no write-off events.

I have tried this using both the built-in DB and also a SQL DB so have verified the application as the problem.

Full exception report follows:
Invalid object name 'dbo.InterestWriteOffEvents'.\n\n
Server stack trace: 
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader()
   at OpenCBS.Manager.Events.EventManager.SelectEvents(Int32 pContractId, SqlTransaction tx)
   at OpenCBS.Manager.Contracts.LoanManager.SelectLoan(Int32 pLoanId, Boolean pAddGeneralInformation, Boolean pAddOptionalInformation, Boolean pAddOptionalEventInformation)
   at OpenCBS.Manager.Contracts.LoanManager.SelectLoansByProject(Int32 pProjectId)
   at OpenCBS.Manager.ProjectManager.SelectProject(Int32 pId)
   at OpenCBS.Manager.ProjectManager.SelectProjectsByClientId(Int32 pClientId)
   at OpenCBS.Manager.Clients.ClientManager.SelectBodyCorporateById(Int32 id)
   at OpenCBS.Services.ClientServices.FindTiers(Int32 tiersId, OClientTypes type)
   at System.Runtime.Remoting.Messaging.Message.Dispatch(Object target)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at OpenCBS.Services.ClientServices.FindTiers(Int32 tiersId, OClientTypes type)
   at OpenCBS.GUI.SearchClientForm.HandleTierSelect(ClientSearchResult pClient)

**Comment by aaron4356** [comment]
This is a bug with the previous version of the software. Please download the latest version (15.5) from here: http://sourceforge.net/projects/opencbs/files/opencbs-15.5/

**Comment by lpetersctc** [comment]
Hi Aaron,

Thanks for that. It seems that it is fine with new databases in 15.5 but any databases created in 15.4 are affected by this bug. Not sure if there is anytihng that can be done?

Luke

**Comment by aaron4356** [comment]
If you want, you can give us the database and we can upgrade it for you. If you don't want to share the database, we may be able to send you a script to solve the issue.

**Comment by lpetersctc** [comment]
It does not matter, I didn't have much in there so worked with a new database. The database did get auto-upgraded to 15.5 though so, strange one.

Thanks though.

**Comment by aaron4356** [comment]
No problem!

**Comment by etiennemottet** [comment]
Hey peter, we are actually interested to know more in what you are doing with our software. If you like join us on skype at info.opencbs and we can see how we can support you better.
